### ISSUE TITLE
Add CTA option to CLI

### ISSUE THREAD

**Issue by msutkowski** [LunchDevCommunity/community-calendar#23]
See https://github.com/LunchDevCommunity/community-calendar/pull/22/files#diff-27d98483d3ba1d9300500ec2037f42bc418fca212da6874e285831bc11ba2a1bR9-R16 for an example.

This could easily be dropped into the template output.

**Comment by BenDMyers** [comment]
My thought on this is that I only want to show this CTA for upcoming events. I also don't think it should be in the Markdown file itself, because I don't really want event authors to have to worry about it — it should "just" work.

Because of that, I'm thinking that this would make more sense as a part of the event layout - probably some sort of conditional templating like:

```liquid
{% if EVENT_IS_UPCOMING %}
<aside class="call-to-action">
   ...
</aside>
{% endif %}
```

The only reason the call-to-action is in two events' Markdown now is because we needed to move quickly so that we could promote the [Hijacking Screenreaders with CSS](https://events.lunch.dev/hijacking-screenreaders-with-css/) link.

I'm super open to input about this, though!

**Comment by msutkowski** [comment]
> My thought on this is that I only want to show this CTA for upcoming events. I also don't think it should be in the Markdown file itself, because I don't really want event authors to have to worry about it — it should "just" work.
> 
> Because of that, I'm thinking that this would make more sense as a part of the event layout - probably some sort of conditional templating like:
> 
> ```
> {% if EVENT_IS_UPCOMING %}
> <aside class="call-to-action">
>    ...
> </aside>
> {% endif %}
> ```
> 
> The only reason the call-to-action is in two events' Markdown now is because we needed to move quickly so that we could promote the [Hijacking Screenreaders with CSS](https://events.lunch.dev/hijacking-screenreaders-with-css/) link.
> 
> I'm super open to input about this, though!

Makes sense to me! In this case, you'd still have to inject the page frontmatter to generate the right cta data/links, ya? So this topic would still be relevant (maybe?)

**Comment by BenDMyers** [comment]
> Makes sense to me! In this case, you'd still have to inject the page frontmatter to generate the right cta data/links, ya? So this topic would still be relevant (maybe?)

Can you help me understand what you mean by "inject the page frontmatter" in this case, @msutkowski?

**Comment by msutkowski** [comment]
Closed by https://github.com/LunchDevCommunity/community-calendar/pull/38/files
